ALTER TABLE `identity_usuarios` ADD `permisos_json` text DEFAULT '[]' NOT NULL;
--> statement-breakpoint
UPDATE `identity_usuarios`
SET `permisos_json` = '["BOARD_VIEW","SALES_MANAGE","RESERVATIONS_MANAGE","CASHBOX_MANAGE","INVENTORY_MANAGE","CATEGORIES_MANAGE","ROOMS_MANAGE","BILLING_MANAGE","DASHBOARD_VIEW","REPORTS_EXPORT","NOTIFICATIONS_MANAGE","SETTINGS_MANAGE","USERS_MANAGE"]'
WHERE `rol` = 'ADMIN';
--> statement-breakpoint
UPDATE `identity_usuarios`
SET `permisos_json` = '["BOARD_VIEW","SALES_MANAGE","RESERVATIONS_MANAGE","CASHBOX_MANAGE","INVENTORY_MANAGE","BILLING_MANAGE"]'
WHERE `rol` = 'RECEPCIONISTA';
